---
title: "Prelim wrangling"
author: "An Bui, Sam Csik"
date: "2/11/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r set up}
#### libraries ####
library(sf)
library(tidyverse)
library(tmap)
library(leaflet)
library(ggrepel)
library(ggspatial)
library(RColorBrewer)
library(raster)

#### data ####
# school enrollment
school_enrollment <- read_csv("school_enrollment.csv") %>% 
  gather("grade", "students", 7:21) %>%
  mutate(race_eth_name = case_when(
    ETHNIC == "0" ~ "Not reported",
    ETHNIC == "1" ~ "AIAN",
    ETHNIC == "2" ~ "Asian",
    ETHNIC == "3" ~ "PIsl",
    ETHNIC == "4" ~ "Filipino",
    ETHNIC == "5" ~ "Latino",
    ETHNIC == "6" ~ "AfricanAm",
    ETHNIC == "7" ~ "White",
    ETHNIC == "9" ~ "Multiple"),
    gender = case_when(
      GENDER == "F" ~ "female",
      GENDER == "M" ~ "male"
    ))

sc_en <- school_enrollment %>% 
  filter(grade != "NA") %>% 
  mutate(grade_num = case_when(
    grade == "KDGN" ~ 0,
    grade == "GR_1" ~ 1, 
    grade == "GR_2" ~ 2,
    grade == "GR_3" ~ 3,
    grade == "GR_4" ~ 4,
    grade == "GR_5" ~ 5, 
    grade == "GR_6" ~ 6, 
    grade == "GR_7" ~ 7, 
    grade == "GR_8" ~ 8, 
    grade == "GR_9" ~ 9, 
    grade == "GR_10" ~ 10, 
    grade == "GR_11" ~ 11, 
    grade == "GR_12" ~ 12
  ))

grades <- c("KDGN", "GR_1", "GR_2", "GR_3", "GR_4", "GR_5", "GR_6", "GR_7", "GR_8", "GR_9", "GR_10", "GR_11", "GR_12")

sc_en$grade <- factor(sc_en$grade, levels = grades)

# number of students rated "Prepared" for college based on a variety of criteria
college_preparedness <- read_csv("college_preparedness.csv")

# educational attainment for CA counties, percent of people age 25 and up with college degree or higher
edu_att <- read_csv("edu_att_filtered.csv") %>% 
       dplyr::select("county_name", "race_eth_code", "race_eth_name", "geotype", "geotypevalue", "geoname",  "county_fips", "region_name", "region_code", "strata_one_code", "strata_one_name", "numerator",   "denominator", "estimate", "LL_95CI", "UL_95CI", "SE", "RSE", "CA_RR")

edu_att$race_eth_code <- as.numeric(edu_att$race_eth_code)
edu_att$race_eth_name <- as.character(edu_att$race_eth_name)
edu_att$geotype <- as.character(edu_att$geotype)
edu_att$geotypevalue <- as.numeric(edu_att$geotypevalue)
edu_att$county_name <- as.character(edu_att$county_name)
edu_att$county_fips <- as.numeric(edu_att$county_fips)
edu_att$region_name <- as.character(edu_att$region_name)
edu_att$region_code <- as.numeric(edu_att$region_code)
edu_att$strata_one_code <- as.numeric(edu_att$strata_one_code)
edu_att$strata_one_name <- as.character(edu_att$strata_one_name)
edu_att$numerator <- as.numeric(edu_att$numerator)
edu_att$denominator <- as.numeric(edu_att$denominator)
edu_att$estimate <- as.numeric(edu_att$estimate)
edu_att$LL_95CI <- as.numeric(edu_att$LL_95CI)
edu_att$UL_95CI <- as.numeric(edu_att$UL_95CI)
edu_att$SE <- as.numeric(edu_att$SE)
edu_att$RSE <- as.numeric(edu_att$RSE)
edu_att$CA_RR <- as.numeric(edu_att$CA_RR)



# merge counties and edu_att
# edu_att_full <- merge(edu_att, ca_counties) %>% 
#   filter(geotype == "CO" &
#            race_eth_name != "Total") %>% 
#   arrange(-estimate)

```

```{r wrangle college preparedness}
#### filter ####
cp_subset <- college_preparedness %>% 
  # filter only for school reports
  filter(rtype == "S" |
           # take out summary rows for all races
           studentgroup != "ALL") %>% 
  # select desired columns
  dplyr::select(cds, rtype, schoolname, districtname, countyname, studentgroup, currdenom, curr_prep, curr_prep_pct, curr_prep_apexam, curr_prep_apexam_pct, curr_prep_ibexam, curr_prep_ibexam_pct, curr_prep_collegecredit, curr_prep_collegecredit_pct)
# idk about this data because there could be individuals who earned "Prepared" by taking AP classes AND fulfilling class requirements, but there's no info on how many students overlap between categories (if that makes sense)
```

```{r educational attainment by county and race}
edu_att_filter <- edu_att %>% 
  filter(geotype == "CO" &
           race_eth_name != "Total")

# write.csv(edu_att, file = "edu_att_filter.csv")

alameda <- edu_att_filter %>% 
  filter(county_name == "Alameda")

edu_att_bar <- ggplot(edu_att_filter, aes(x = race_eth_name, y = estimate)) +
  geom_bar(stat = "identity") +
  facet_wrap(~county_name)
edu_att_bar

edu_att_alameda <- ggplot(alameda, aes(x = reorder(race_eth_name, -estimate), 
                                       y = estimate)) +
  geom_bar(stat = "identity", aes(fill = race_eth_name)) +
  scale_fill_brewer(palette = "YlGnBu") +
  theme_minimal() +
  labs(x = "Race", 
       y = "Percentage with college degree or higher", 
       title = "Percentage of population 25 years or older with college degree or higher - Alameda County")
edu_att_alameda
```

```{r test wrangle for Amelia Earhart Elementary in Alameda County}
alameda_amear <- sc_en %>% 
  filter(COUNTY == "Alameda" &
           SCHOOL == "Amelia Earhart Elementary" &
           grade_num < 6)

alameda_schools_plot <- ggplot(alameda_amear, aes(x = grade, y = students)) +
  geom_bar(stat = "identity", position = "dodge", aes(fill = race_eth_name)) +
  scale_fill_brewer(palette = "Spectral") +
  facet_wrap(~gender) +
  theme_minimal()
alameda_schools_plot
```

```{r map}
# California counties
ca_counties <- read_sf(".", layer = "california_county_shape_file") %>% 
  dplyr::select(NAME) %>% 
  rename(county_name = NAME)

# set coordinate system to be 4326
st_crs(ca_counties) = 4326

ca_counties_merge <- ca_counties

# try merging ca_counties with school enrollment
school_enrollment_merge <- school_enrollment %>% 
  dplyr::select(COUNTY, DISTRICT, SCHOOL) %>% 
  rename(county_name = COUNTY) %>% 
  unique()

county_schools <- merge(school_enrollment_merge, ca_counties_merge)

alameda_schools <- county_schools %>% 
  filter(county_name == "Alameda")

plot(alameda_schools)

# is this different??

```

